name: GitArtwork on Contribution Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 매일 정기적으로 실행 (UTC 기준)

jobs:
  gitartwork:
    runs-on: ubuntu-latest
    steps:
      - name: GitArtwork on Contribution Graph
        uses: git-artwork/gitartwork-on-contribution-graph@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
